version: "3.7"

services:
  reverse-proxy:
    image: "nginxproxy/nginx-proxy:latest"
    container_name: "proxy"
    volumes:
      - "conf:/etc/nginx/conf.d"
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks:
      - "docker-net"
    ports:
      - "80:80"
      - "443:443"
      - "8978:8978"
      - "9000:9000"
      - "8001:8001"

  letsencrypt:
    image: "nginxproxy/acme-companion:latest"
    container_name: "proxy-ssl"
    volumes:
      - "conf:/etc/nginx/conf.d"
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      DEFAULT_EMAIL: "jesus.tirado@innovait.cat"
#      NGINX_DOCKER_GEN_CONTAINER: "proxy-gen"
    restart: "always"
    depends_on:
      - "reverse-proxy"
    networks:
      - "docker-net"
volumes:
  conf:
  certs:
  html:
  vhost:
  dhparam:

networks:
  docker-net:
    external: true
